request:
  method: GET
  path: /v3/partner/*/patchstatus
control:
  delay: "3ms"
response:
  statusCode: 200
  body: >
    {
      "patchStatustList": [
        {
          "regId": 53758917,
          "siteId": 50110859,
          "status": "Not Seen Recently",
          "osStatus": "Not Seen Recently",
          "tpStatus": "Not Seen Recently"
        },
        {
          "regId": 53758935,
          "siteId": 50110859,
          "status": "Not Seen Recently",
          "osStatus": "Not Seen Recently",
          "tpStatus": "Not Seen Recently"
        },
        {
          "regId": 53758937,
          "siteId": 50110859,
          "status": "Not Seen Recently",
          "osStatus": "Not Seen Recently",
          "tpStatus": "Not Seen Recently"
        },
        {
          "regId": 53759211,
          "siteId": 50110883,
          "status": "Not Seen Recently",
          "osStatus": "Not Seen Recently",
          "tpStatus": "Not Seen Recently"
        },
        {
          "regId": 53879144,
          "siteId": 50122438,
          "status": "Not Seen Recently",
          "osStatus": "Not Seen Recently",
          "tpStatus": "Not Seen Recently"
        },
        {
          "regId": 53879520,
          "siteId": 50122123,
          "status": "Not Seen Recently",
          "osStatus": "Not Seen Recently",
          "tpStatus": "Not Seen Recently"
        },
        {
          "regId": 53880003,
          "siteId": 50110883,
          "status": "Not Seen Recently",
          "osStatus": "Not Seen Recently",
          "tpStatus": "Not Seen Recently"
        },
        {
          "regId": 53879398,
          "siteId": 50122438,
          "status": "Not Seen Recently",
          "osStatus": "Not Seen Recently",
          "tpStatus": "Not Seen Recently"
        }
      ],
      "totalCount": 8,
      "timeLogs": null
    }