request:
  method: GET
  path: /v1/partner/50016338/sites
control:
  delay: "10ms"
response:
  statusCode: 200
  body: >
    {
      "siteDetailList": [
        {
          "siteName": "Arizona",
          "siteCode": "AZ",
          "siteId": 50122438,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "ARIZONA",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1/oQN2pRIPzhG9yC8vJ0xUSti2YjI+fwlo=",
          "industryID": 1,
          "industrySector": "11",
          "description": "Agriculture, Forestry, Fishing and Hunting"
        },
        {
          "siteName": "DefaultAutomationSite",
          "siteCode": "dt-02",
          "siteId": 50110883,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "AKST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X18fSlKtQR9DwpNQ3UANUHCDDmikBUchkAc=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "K1",
          "siteCode": "K1",
          "siteId": 50121303,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "LONDON",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1+g3EKSOfcxH07RT24VsO6hccRzEL3CZ5A=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "K2",
          "siteCode": "K2",
          "siteId": 50121304,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "HST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1950oJLqpQD8BaYSM+ECEsU9W3bgXi+gkQ=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "qaDNSP3",
          "siteCode": "qaDNSP3",
          "siteId": 50110877,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "INDIA",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X180uaPt95tKec8lohaoGDeuEzWVYy6tRwM=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "qaDNSP4",
          "siteCode": "qaDNSP4",
          "siteId": 50110878,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "CET",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1/JdAHUE01y94lvwcu1dgI3zHwLw+VVBxM=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "qaEnableDisableDNSP",
          "siteCode": "qaEnableDisableDNSP",
          "siteId": 50110884,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "NST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X18EtB6+Bfn9NGiMQgmWUWa5szT1Cft2FeM=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "qaTestDNSP",
          "siteCode": "qaTestDNSP",
          "siteId": 50110874,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "NST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X18tXnUrMV82DSJsnmWW2vutLwd1JjiO2mQ=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "qwerty123",
          "siteCode": "qwerty123",
          "siteId": 50110882,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "IEST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1+Jvwab9FZCQPtzu+2lBXsysbrd5CNf3cI=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "secureSiteA",
          "siteCode": "secureSiteA",
          "siteId": 50122125,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "IDLW",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X18YVSN2/MZAxT3iMtSETXAh52qFJ0d3nyE=",
          "industryID": 20,
          "industrySector": "82",
          "description": "Public Administration"
        },
        {
          "siteName": "secureSiteB",
          "siteCode": "secureSiteB",
          "siteId": 50122139,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "Azores",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X197NSQmzV36V5DUiaooGB2fIdkdTXkAKTs=",
          "industryID": 1,
          "industrySector": "11",
          "description": "Agriculture, Forestry, Fishing and Hunting"
        },
        {
          "siteName": "secureSiteC",
          "siteCode": "secureSiteC",
          "siteId": 50122140,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "Azores",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X18Kbsr+n36rNEDCDKlq0ZbrUAJxro1eGTQ=",
          "industryID": 17,
          "industrySector": "71",
          "description": "Arts, Entertainment, and Recreation"
        },
        {
          "siteName": "secureSiteD",
          "siteCode": "secureSiteD",
          "siteId": 50122141,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "Azores",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X18erHbYO0qzglMrt+lS/zRAebNmMhDKxpw=",
          "industryID": 1,
          "industrySector": "11",
          "description": "Agriculture, Forestry, Fishing and Hunting"
        },
        {
          "siteName": "Site to test deactivate",
          "siteCode": "ww",
          "siteId": 50110989,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "PST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1+k06TV0IsbQY8S++tCCOBtnZOZcwWiqvc=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "SiteA",
          "siteCode": "SiteA",
          "siteId": 50122123,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "RST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X197YJvLxcxgbQWlKAJsZmDfeHhMBW9jo68=",
          "industryID": 20,
          "industrySector": "82",
          "description": "Public Administration"
        },
        {
          "siteName": "siteB",
          "siteCode": "siteB",
          "siteId": 50122124,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "Azores",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X19nMexc7qik++EF/Sn7aiTDH8W6OwO2IVg=",
          "industryID": 20,
          "industrySector": "82",
          "description": "Public Administration"
        },
        {
          "siteName": "SiteWithContacts",
          "siteCode": "VitaliyLtestSiteCreation",
          "siteId": 50120811,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "Jerusalem",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X18qcBtjNOjLMSwgPMI2bVNyRkH7YX4NfHk=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "SiteWithEndpoints",
          "siteCode": "site-01-one-endpoint-sc",
          "siteId": 50110859,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "SAST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1+RJfQmQWeoheDnCi1R6OHijS45DwoaHqo=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "Test123",
          "siteCode": "Test123",
          "siteId": 50121244,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "ARIZONA",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X19es8kITRjN9Zc3pV/EVEDWkjeW1jtx4pg=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "Test-K1",
          "siteCode": "Test-K1",
          "siteId": 50121247,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "HST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X18s2rRAx9tjVC/uJlMoURDfxAcXp8+OjeI=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "TestWR1234",
          "siteCode": "TestWR1234",
          "siteId": 50121246,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "HST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1+H+8Vp9IMBPI3wGQ1msGBPYs8qLQIh+7s=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "TestWRDNS2",
          "siteCode": "TestWRDNS2",
          "siteId": 50110870,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "AKST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1+U2XVGnfBwPPe/Y0g29T1Qyzz0RaOUSqc=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "TestWRDNS5656",
          "siteCode": "TestWRDNS5656",
          "siteId": 50110880,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "PST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X180xuQQ1ZrxIT3NclO+BG47HjVfOdUFRyA=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "TestWRdns7878",
          "siteCode": "TestWRdns7878",
          "siteId": 50110881,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "AKST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1+heyPT6sHHy2aID0BG0dgeXj93hsbk1aE=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "Webroot Dns Site -1",
          "siteCode": "WebrootDnsSite-1",
          "siteId": 50121236,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "INDIA",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X18caNgTQnemvWNdF3ux2u9ePooSxDu8rn0=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "WebrootDNSNewAPI07Dec",
          "siteCode": "WebrootDNSNewAPI07Dec",
          "siteId": 50120772,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "CCST",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X18eFd6KfAi9UNd7yyA8vmpUAFj8azsSyhI=",
          "industryID": null,
          "industrySector": null,
          "description": null
        },
        {
          "siteName": "webrootdnssite22",
          "siteCode": "webrootdnssite22",
          "siteId": 50110871,
          "helpDesk": "No",
          "desktopOption": "Essential",
          "serverOption": "Elite",
          "serverServiceId": 6,
          "desktopServiceId": 11,
          "timeZone": "INDIA",
          "timediff": null,
          "zoneDisplayName": null,
          "encSiteId": "SVRTMjQ3X1/pOWhQ0/ykO9am8scuZG+yX4L2jNXdsNY=",
          "industryID": null,
          "industrySector": null,
          "description": null
        }
      ]
    }